# frozen_string_literal: true

# Generated by tools/generate-formula on release. Edits are overwritten.
class Adocfmt < Formula
  desc "Opinionated AsciiDoc formatter"
  homepage "https://github.com/ypfaff/adocfmt"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.4.1/adocfmt_0.4.1_darwin_arm64.tar.gz"
      sha256 "ceaef0817bde2c2121779a4bc7dab7106e92ead4f06328055d773eec1e58485f"
    end
    on_intel do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.4.1/adocfmt_0.4.1_darwin_amd64.tar.gz"
      sha256 "ad00f23f14460becdcb7864d3627845554cb57e3161af673ec3e7a0407df073f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.4.1/adocfmt_0.4.1_linux_arm64.tar.gz"
      sha256 "4aeec08196216196291d30fbb5da793734f6c8a9f9d3828a17ec15e303ae272a"
    end
    on_intel do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.4.1/adocfmt_0.4.1_linux_amd64.tar.gz"
      sha256 "7dff76ed15fedf30cd8e184e5ac6698f9be935b1a5ba6d5555b0ed5b98f3d411"
    end
  end

  def install
    bin.install "adocfmt"
  end

  # Formatting a document rather than --version, which passes while the
  # formatter is broken.
  test do
    (testpath/"test.adoc").write("## Section ##\n")
    assert_equal "== Section\n", shell_output("#{bin}/adocfmt #{testpath}/test.adoc")
  end
end
