# frozen_string_literal: true

# Generated by tools/generate-formula on release. Edits are overwritten.
class Adocfmt < Formula
  desc "Opinionated AsciiDoc formatter"
  homepage "https://github.com/ypfaff/adocfmt"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.3.0/adocfmt_0.3.0_darwin_arm64.tar.gz"
      sha256 "ef17fbcf90e848d21f58842097f3962d5ec186a8fbab1366dd95d2568c556edd"
    end
    on_intel do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.3.0/adocfmt_0.3.0_darwin_amd64.tar.gz"
      sha256 "0876ebe8459cbd8dbbfc145232a080d3a17995437460b5dedbc41ee4195f6300"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.3.0/adocfmt_0.3.0_linux_arm64.tar.gz"
      sha256 "21aa833ef549c13c34c5651868a23ba96fdaeaf06015e7de02c8c70b87a6a7f9"
    end
    on_intel do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.3.0/adocfmt_0.3.0_linux_amd64.tar.gz"
      sha256 "a08813a653389adcd74d0cdb9ad4ff580f5473af313a79b1740ce649b185364d"
    end
  end

  def install
    bin.install "adocfmt"
  end

  # Formatting a document rather than --version, which passes while the
  # formatter is broken.
  test do
    (testpath/"test.adoc").write("## Section ##\n")
    assert_equal "== Section\n", shell_output("#{bin}/adocfmt #{testpath}/test.adoc")
  end
end
