# frozen_string_literal: true

# Generated by tools/generate-formula on release. Edits are overwritten.
class Adocfmt < Formula
  desc "Opinionated AsciiDoc formatter"
  homepage "https://github.com/ypfaff/adocfmt"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.3.1/adocfmt_0.3.1_darwin_arm64.tar.gz"
      sha256 "9724d5379707ec3a0b1bc896bd1164db24d326fb723462f266e97e12b6ce7ecd"
    end
    on_intel do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.3.1/adocfmt_0.3.1_darwin_amd64.tar.gz"
      sha256 "9a023768593d19191acfd84fa47e911f46d4c7e1903cc37b30628d7c4012a03b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.3.1/adocfmt_0.3.1_linux_arm64.tar.gz"
      sha256 "4c104acc985a8fdeefbfd81f818878e5bff83178cefd1f3f0df96fcb71f7fd23"
    end
    on_intel do
      url "https://github.com/ypfaff/adocfmt/releases/download/v0.3.1/adocfmt_0.3.1_linux_amd64.tar.gz"
      sha256 "9c3135f76208505cb842ed5742fa4c6d032feba340d573f64a08f72554e76aad"
    end
  end

  def install
    bin.install "adocfmt"
  end

  # Formatting a document rather than --version, which passes while the
  # formatter is broken.
  test do
    (testpath/"test.adoc").write("## Section ##\n")
    assert_equal "== Section\n", shell_output("#{bin}/adocfmt #{testpath}/test.adoc")
  end
end
