#!/usr/bin/env bash
#
# Write the Homebrew formula for a release from the checksums GoReleaser left in
# dist/. Runs on Linux and macOS.

set -o errexit -o nounset -o pipefail

readonly SCRIPT_NAME="${0##*/}"

# The formula names an URL per platform, so it carries no repository of its own
# to derive one from.
readonly REPOSITORY="ypfaff/adocfmt"

# Homebrew runs on these four; the release also builds Windows, which has no
# formula.
readonly PLATFORMS=("darwin arm64" "darwin amd64" "linux arm64" "linux amd64")

usage() {
  cat <<EOF
Usage: ${SCRIPT_NAME} --version X.Y.Z --checksums FILE --output FILE

Write the Homebrew formula for a released version.

Options:
  --version VERSION  The released version, without the leading v.
  --checksums FILE   GoReleaser's checksums.txt.
  --output FILE      Where to write the formula.
  --help             Print this help.
EOF
}

err() {
  echo "${SCRIPT_NAME}: $*" >&2
  exit 1
}

archive_name() {
  local os="$1" arch="$2"
  echo "adocfmt_${VERSION}_${os}_${arch}.tar.gz"
}

# One url/sha256 pair, indented to sit inside an on_arm or on_intel block. The
# URL also carries the version: Homebrew reads it from there, and brew audit
# rejects a version field next to it as redundant.
platform_block() {
  local archive sha
  archive="$(archive_name "$1" "$2")"
  sha="$(awk -v want="${archive}" '$2 == want { print $1 }' "${CHECKSUMS}")"
  cat <<EOF
      url "https://github.com/${REPOSITORY}/releases/download/v${VERSION}/${archive}"
      sha256 "${sha}"
EOF
}

# A lookup that fails inside the template below would return an empty string
# rather than stop the script, so every archive is checked before anything is
# written.
require_checksums() {
  local platform os arch archive
  for platform in "${PLATFORMS[@]}"; do
    read -r os arch <<<"${platform}"
    archive="$(archive_name "${os}" "${arch}")"
    grep -q " ${archive}\$" "${CHECKSUMS}" ||
      err "${CHECKSUMS} holds no checksum for ${archive}"
  done
}

write_formula() {
  cat >"${OUTPUT}" <<EOF
# frozen_string_literal: true

# Generated by .github/scripts/${SCRIPT_NAME} on release. Edits are overwritten.
class Adocfmt < Formula
  desc "Opinionated AsciiDoc formatter"
  homepage "https://github.com/${REPOSITORY}"
  license "Apache-2.0"

  on_macos do
    on_arm do
$(platform_block darwin arm64)
    end
    on_intel do
$(platform_block darwin amd64)
    end
  end

  on_linux do
    on_arm do
$(platform_block linux arm64)
    end
    on_intel do
$(platform_block linux amd64)
    end
  end

  def install
    bin.install "adocfmt"
  end

  # Formatting a document rather than --version, which passes while the
  # formatter is broken.
  test do
    (testpath/"test.adoc").write("## Section ##\n")
    assert_equal "== Section\n", shell_output("#{bin}/adocfmt #{testpath}/test.adoc")
  end
end
EOF
}

main() {
  VERSION=""
  CHECKSUMS=""
  OUTPUT=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --version) VERSION="${2:-}"; shift 2 ;;
      --checksums) CHECKSUMS="${2:-}"; shift 2 ;;
      --output) OUTPUT="${2:-}"; shift 2 ;;
      --help) usage; exit 0 ;;
      *) err "unknown option $1" ;;
    esac
  done

  [[ -n "${VERSION}" ]] || err "--version is required"
  [[ -n "${CHECKSUMS}" ]] || err "--checksums is required"
  [[ -n "${OUTPUT}" ]] || err "--output is required"
  [[ -r "${CHECKSUMS}" ]] || err "cannot read ${CHECKSUMS}"

  VERSION="${VERSION#v}"
  require_checksums
  mkdir -p "$(dirname "${OUTPUT}")"
  write_formula
  echo "${SCRIPT_NAME}: wrote ${OUTPUT} for v${VERSION}" >&2
}

main "$@"
