= image:docs/images/adocfmt-icon.svg[adocfmt icon,40] adocfmt

An opinionated AsciiDoc® formatter.

CAUTION: adocfmt is early work in progress.
Its rules and their output can still change between releases.

== Documentation

The documentation is published at https://ypfaff.github.io/adocfmt/.

* xref:docs/getting-started.adoc[Get started with adocfmt]
* xref:docs/how-to/install.adoc[Install adocfmt]
* xref:docs/reference/rules.adoc[Formatting rules]
* link:docs[All documentation]

== Contributing

xref:CONTRIBUTING.adoc[Contributing] explains how to work on adocfmt.

== Security

link:SECURITY.md[Security policy] explains how to report a vulnerability.

== License

Apache License 2.0; see link:LICENSE[`LICENSE`] and link:NOTICE[`NOTICE`].

The cases under link:testdata/asciidoctor-cases[`testdata/asciidoctor-cases`] are test inputs of the Asciidoctor test suite and stay under its MIT license, which sits next to them.

The link:CODE_OF_CONDUCT.adoc[Code of Conduct] is adapted from the Contributor Covenant and stays under its CC BY-SA 4.0 license.

AsciiDoc® and AsciiDoc Language™ are trademarks of the Eclipse Foundation, Inc.
