// Package corpus locates the Asciidoctor cases: one file per test input of the
// Asciidoctor test suite, generated by tools/fetch-asciidoctor-cases.
//
// See docs/testing-strategy.adoc for what the cases cover.
package corpus

import (
	"fmt"
	"io/fs"
	"path/filepath"
	"strings"
)

// Dir holds the cases, relative to the repository root.
const Dir = "testdata/asciidoctor-cases"

// Files returns every case below root, in path order. The README the generator
// leaves next to them is not a case.
func Files(root string) ([]string, error) {
	var files []string
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() && filepath.Ext(path) == ".adoc" && entry.Name() != "README.adoc" {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("reading the cases: %w", err)
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("no cases in %s; run go run ./tools/fetch-asciidoctor-cases", root)
	}
	return files, nil
}

// Name is the case name of a file below root: its path without the root and
// the extension, so it reads the same on every platform.
func Name(root, path string) string {
	rel := strings.TrimPrefix(filepath.ToSlash(path), filepath.ToSlash(root)+"/")
	return strings.TrimSuffix(rel, ".adoc")
}
