// Command fetch-asciidoctor-cases regenerates testdata/asciidoctor-cases from
// the Asciidoctor test suite:
//
//	go run ./tools/fetch-asciidoctor-cases
//
// The --print-version flag prints the pinned Asciidoctor version instead, which
// is how CI learns which Asciidoctor to install.
//
// See docs/testing-strategy.adoc for what the cases are and how they are used.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ypfaff/adocfmt/internal/corpus"
	"github.com/ypfaff/adocfmt/internal/repo"
)

const (
	// asciidoctorTag pins the cases so regenerating them is reproducible. It
	// tracks the Asciidoctor release the checks render with.
	asciidoctorTag = "v2.0.26"
	asciidoctorURL = "https://github.com/asciidoctor/asciidoctor"
)

func main() {
	log.SetFlags(0)

	printVersion := flag.Bool("print-version", false, "print the pinned Asciidoctor version and exit")
	flag.Parse()

	if *printVersion {
		fmt.Println(strings.TrimPrefix(asciidoctorTag, "v"))
		return
	}

	if err := run(); err != nil {
		log.Fatalln("error:", err)
	}
}

func run() error {
	root, err := repo.Root()
	if err != nil {
		return err
	}
	casesDir := filepath.Join(root, corpus.Dir)

	checkout, err := os.MkdirTemp("", "asciidoctor")
	if err != nil {
		return err
	}
	defer os.RemoveAll(checkout)

	log.Printf("cloning %s at %s", asciidoctorURL, asciidoctorTag)
	clone := exec.Command("git", "clone", "--quiet", "--depth", "1",
		"--config", "advice.detachedHead=false", "--branch", asciidoctorTag, asciidoctorURL, checkout)
	clone.Stderr = os.Stderr
	if err := clone.Run(); err != nil {
		return fmt.Errorf("cloning Asciidoctor: %w", err)
	}

	if err := os.RemoveAll(casesDir); err != nil {
		return err
	}

	sources, err := filepath.Glob(filepath.Join(checkout, "test", "*_test.rb"))
	if err != nil {
		return err
	}
	sort.Strings(sources)

	total := 0
	for _, source := range sources {
		written, err := writeCases(source, casesDir)
		if err != nil {
			return err
		}
		if written > 0 {
			log.Printf("%6d  %s", written, strings.TrimSuffix(filepath.Base(source), "_test.rb"))
			total += written
		}
	}

	if err := writeLicense(checkout, casesDir); err != nil {
		return err
	}
	if err := writeReadme(casesDir, total); err != nil {
		return err
	}
	log.Printf("%d cases in %s", total, corpus.Dir)
	return nil
}

// writeCases extracts one Ruby test file into its own directory and reports how
// many cases it held.
func writeCases(source, casesDir string) (int, error) {
	ruby, err := os.ReadFile(source)
	if err != nil {
		return 0, err
	}

	cases := extract(string(ruby))
	if len(cases) == 0 {
		return 0, nil
	}

	dir := filepath.Join(casesDir, strings.TrimSuffix(filepath.Base(source), "_test.rb"))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return 0, err
	}
	for i, testCase := range cases {
		if err := os.WriteFile(testCase.path(dir, i+1), []byte(testCase.body), 0o644); err != nil {
			return 0, err
		}
	}
	return len(cases), nil
}

// writeLicense puts Asciidoctor's license next to the cases, because the MIT
// permission notice has to travel with them. Taking it from the checkout keeps
// the text in step with the pinned tag.
func writeLicense(checkout, casesDir string) error {
	license, err := os.ReadFile(filepath.Join(checkout, "LICENSE"))
	if err != nil {
		return fmt.Errorf("reading Asciidoctor's license: %w", err)
	}
	return os.WriteFile(filepath.Join(casesDir, "LICENSE"), license, 0o644)
}

func writeReadme(casesDir string, cases int) error {
	readme := fmt.Sprintf(`= Asciidoctor cases

Generated by link:../../tools/fetch-asciidoctor-cases[`+"`tools/fetch-asciidoctor-cases`"+`]; do not edit by hand.

Each file is one test input from the Asciidoctor test suite at %s.
Directory names follow the Ruby test file, file names the test the input belongs to.

See link:../../docs/testing-strategy.adoc[the testing strategy] for what these cases cover.

Source: %s, MIT License (link:LICENSE[`+"`LICENSE`"+`]), Copyright (C) 2012-present Dan Allen, Sarah White, Ryan Waldron and the individual contributors to Asciidoctor.

Cases: %d
`, asciidoctorTag, asciidoctorURL, cases)

	return os.WriteFile(filepath.Join(casesDir, "README.adoc"), []byte(readme), 0o644)
}
