# frozen_string_literal: true

# Generated by tools/generate-formula on release. Edits are overwritten.
class Adocfmt < Formula
  desc "Opinionated AsciiDoc formatter"
  homepage "https://github.com/ypfaff/adocfmt"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ypfaff/adocfmt/releases/download/v1.2.3/adocfmt_1.2.3_darwin_arm64.tar.gz"
      sha256 "2222222222222222222222222222222222222222222222222222222222222222"
    end
    on_intel do
      url "https://github.com/ypfaff/adocfmt/releases/download/v1.2.3/adocfmt_1.2.3_darwin_amd64.tar.gz"
      sha256 "1111111111111111111111111111111111111111111111111111111111111111"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ypfaff/adocfmt/releases/download/v1.2.3/adocfmt_1.2.3_linux_arm64.tar.gz"
      sha256 "4444444444444444444444444444444444444444444444444444444444444444"
    end
    on_intel do
      url "https://github.com/ypfaff/adocfmt/releases/download/v1.2.3/adocfmt_1.2.3_linux_amd64.tar.gz"
      sha256 "3333333333333333333333333333333333333333333333333333333333333333"
    end
  end

  def install
    bin.install "adocfmt"
  end

  # Formatting a document rather than --version, which passes while the
  # formatter is broken.
  test do
    (testpath/"test.adoc").write("## Section ##\n")
    assert_equal "== Section\n", shell_output("#{bin}/adocfmt #{testpath}/test.adoc")
  end
end
