package format

import (
	"errors"
	"slices"
	"strings"
	"testing"
)

// TestFormatRefuses pins that a document the parser could not read safely
// comes back as an error naming every finding, and never as output.
func TestFormatRefuses(t *testing.T) {
	t.Parallel()

	out, err := Format([]byte("ifdef::extra[]\n----\nendif::[]\ncode\n"))
	if out != nil {
		t.Errorf("got output %q, want none", out)
	}
	want := "line 2: block has no closing delimiter\nline 2: delimiter opens and closes in different conditional regions"
	if err == nil || err.Error() != want {
		t.Errorf("got error %v, want %q", err, want)
	}
}

// TestFormatRefusalCarriesFindings pins that a caller reaches the line of every
// finding, which is what lets the command write path:line: message.
func TestFormatRefusalCarriesFindings(t *testing.T) {
	t.Parallel()

	_, err := Format([]byte("ifdef::extra[]\n\n----\ncode\n"))

	var refusal *Refusal
	if !errors.As(err, &refusal) {
		t.Fatalf("got error %v, want a *Refusal", err)
	}
	want := []Finding{
		{Line: 1, Message: "conditional region has no endif"},
		{Line: 3, Message: "block has no closing delimiter"},
	}
	if !slices.Equal(refusal.Findings, want) {
		t.Errorf("got %+v, want %+v", refusal.Findings, want)
	}
}

// TestFormatRejects pins that source the parser must not repair silently is
// refused with a reason, and that it is no Refusal: it names no line, so the
// command has nothing to place it on.
func TestFormatRejects(t *testing.T) {
	t.Parallel()

	_, err := Format([]byte("a\r\nb\n"))
	if err == nil || !strings.Contains(err.Error(), "mixed line endings") {
		t.Errorf("got error %v, want one about mixed line endings", err)
	}

	var refusal *Refusal
	if errors.As(err, &refusal) {
		t.Errorf("got a *Refusal, want a plain error")
	}
}

// TestRefusalWithoutFindings pins that the exported type answers rather than
// panics when it holds nothing, which errors.As lets a caller reach.
func TestRefusalWithoutFindings(t *testing.T) {
	t.Parallel()

	for name, refusal := range map[string]*Refusal{"nil": nil, "empty": {}} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			if got, want := refusal.Error(), "refused without a finding"; got != want {
				t.Errorf("got %q, want %q", got, want)
			}
		})
	}
}

// TestIgnoreFileLeavesTheSource pins that the directive above the title hands
// the source back byte for byte, a source Parse rejects or refuses included.
func TestIgnoreFileLeavesTheSource(t *testing.T) {
	t.Parallel()

	for name, src := range map[string]string{
		"alone":                  "// adocfmt: ignore-file\n= T\n\nA.  B.\n",
		"with a reason":          "// adocfmt: ignore-file generated by apidoc\nA.  B.\n",
		"with a reason by a tab": "// adocfmt: ignore-file\tgenerated\nA.  B.\n",
		"blanks around it":       "// \t adocfmt: ignore-file \t\nA.  B.\n",
		"no blank after slashes": "//adocfmt: ignore-file\nA.  B.\n",
		"byte order mark":        "\xef\xbb\xbf// adocfmt: ignore-file\nA.  B.\n",
		"crlf":                   "// adocfmt: ignore-file\r\nA.  B.\r\n",
		"front matter":           "---\ntitle: x\n---\n\n// adocfmt: ignore-file\nA.  B.\n",
		"under other comments":   "// one\n\n////\nblock\n////\n// adocfmt: ignore-file\n= T\n",
		"above a fence":          "// adocfmt: ignore-file\n---\na: b\n---\nA.  B.\n",
		"mixed line endings":     "// adocfmt: ignore-file\r\nA.  B.\n",
		"invalid utf-8":          "// adocfmt: ignore-file\n\xff\n",
		"unclosed block":         "// adocfmt: ignore-file\n\n----\ncode\n",
		"unclosed comment block": "// adocfmt: ignore-file\n////\nx\n",
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			out, err := Format([]byte(src))
			if err != nil || string(out) != src {
				t.Errorf("got %q, %v; want the source back", out, err)
			}
		})
	}
}

// TestIgnoreFileElsewhereIsAComment pins that only the exact spelling above
// the title counts, and that nothing below the title is read for it.
func TestIgnoreFileElsewhereIsAComment(t *testing.T) {
	t.Parallel()

	for name, src := range map[string]string{
		"upper case":               "// ADOCFMT: ignore-file\n\nA.  B.\n",
		"dash":                     "// adocfmt-ignore-file\n\nA.  B.\n",
		"no colon":                 "// adocfmt ignore-file\n\nA.  B.\n",
		"three slashes":            "/// adocfmt: ignore-file\n\nA.  B.\n",
		"indented":                 " // adocfmt: ignore-file\n\nA.  B.\n",
		"in the body":              "A.  B.\n\n// adocfmt: ignore-file\n// adocfmt: off\n",
		"under toml":               "+++\ntitle = \"x\"\n+++\n\n// adocfmt: ignore-file\n\nA.  B.\n",
		"under an attribute":       ":a: b\n// adocfmt: ignore-file\n= T\n\nA.  B.\n",
		"in a comment block":       "////\n// adocfmt: ignore-file\n////\n\nA.  B.\n",
		"under the title":          "= T\n// adocfmt: ignore-file\n\nA.  B.\n",
		"in the header":            "= T\nAuthor\n:a: b\n// adocfmt: ignore-file\n\nA.  B.\n",
		"misspelled":               "// adocfmt: ignore-flie\n\nA.  B.\n",
		"a suffix":                 "// adocfmt: ignore-files\n\nA.  B.\n",
		"no blank after the colon": "//adocfmt:ignore-file\n\nA.  B.\n",
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			out, err := Format([]byte(src))
			if err != nil || string(out) == src {
				t.Errorf("got %q, %v; want it formatted", out, err)
			}
		})
	}
}
